### PR TITLE
fix for hide config panel on scroll

### LINKED ISSUE #633: Hide config panel on scroll
Config panel remains open on scroll:
Peek 2022-01-12 18-16

---

All the status bars should extend `VisibleAreaListener`. You can use that to close the config panel.

### PR DESCRIPTION
**Pull request by javamak**

### CODE REVIEW

File: plugin/src/main/java/spp/jetbrains/sourcemarker/settings/LiveLogConfigurationPanel.java [hunk 1]
```diff
@@ -49,15 +50,15 @@ public LiveLogConfigurationPanel(AutocompleteField autocompleteField, InlayMark
             try {
                 editorsProvider = (XDebuggerEditorsProvider) Class.forName(
                         "com.jetbrains.python.debugger.PyDebuggerEditorsProvider"
-                ).newInstance();
+                ).getDeclaredConstructor().newInstance();
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/settings/LiveLogConfigurationPanel.java:53]: Please explain this change

Comment (javamak) [reply plugin/src/main/java/spp/jetbrains/sourcemarker/settings/LiveLogConfigurationPanel.java:53]: class.newInstance is deprecated and this is the alternate suggested.

File: plugin/src/main/java/spp/jetbrains/sourcemarker/settings/LiveLogConfigurationPanel.java [hunk 2]
```diff
@@ -39,6 +39,7 @@
 
     public LiveLogConfigurationPanel(AutocompleteField autocompleteField, InlayMark inlayMark) {
         PsiFile psiFile = inlayMark.getSourceFileMarker().getPsiFile();
+
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/settings/LiveLogConfigurationPanel.java]:
```suggestion
```
