### PR TITLE
Fixed issues 599, 600 and 601

### LINKED ISSUE #599: Consolidate IconLoader.getIcon
Move all `IconLoader.getIcon()` calls to `SourceMarkerIcons.kt`.

### LINKED ISSUE #600: Consolidate Color()
Move all `new Color()` constructions (in UI Java files) to `SourceMarkerPlugin` (i.e. SourceMarkerPlugin.SOURCE_RED)

### LINKED ISSUE #601: Bundle necessary fonts with plugin

### PR DESCRIPTION
**Pull request by javamak**

### CODE REVIEW

File: plugin/src/main/java/spp/jetbrains/sourcemarker/PluginUI.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+            ROBOTO_LIGHT_PLAIN_15 = ROBOTO_LIGHT.deriveFont(Font.PLAIN).deriveFont(15f);
+            ROBOTO_LIGHT_PLAIN_16 = ROBOTO_LIGHT.deriveFont(Font.PLAIN).deriveFont(16f);
+        } catch (FontFormatException e) {
+            e.printStackTrace();
+        } catch (IOException e) {
+            e.printStackTrace();
+        }
+    }
+
+    /*public static final Font ROBOTO_LIGHT_BOLD_14 = new Font("Roboto Light", Font.BOLD, 14);
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/PluginUI.java]: Remove code instead of commenting out

File: plugin/src/main/java/spp/jetbrains/sourcemarker/status/BreakpointStatusBar.java [hunk 2]
```diff
@@ -155,13 +168,13 @@ private void removeActiveDecorations() {
         SwingUtilities.invokeLater(() -> {
             if (expandLabel != null) expandLabel.setIcon(PluginIcons.expand);
             closeLabel.setIcon(PluginIcons.close);
-            configPanel.setBackground(PluginColors.getBackgroundDefault());
+            configPanel.setBackground(spp.jetbrains.sourcemarker.PluginUI.getBackgroundDefaultColor());
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/status/BreakpointStatusBar.java]: You have several fully qualified references in this PR. Please remove

File: plugin/src/main/java/spp/jetbrains/sourcemarker/PluginUI.java (hunk 1 above)
Comment (javamak) [reply plugin/src/main/java/spp/jetbrains/sourcemarker/PluginUI.java]: Removed

File: plugin/src/main/java/spp/jetbrains/sourcemarker/status/BreakpointStatusBar.java (hunk 2 above)
Comment (javamak) [reply plugin/src/main/java/spp/jetbrains/sourcemarker/status/BreakpointStatusBar.java]: Fixed

File: plugin/src/main/java/spp/jetbrains/sourcemarker/status/MeterStatusBar.java [hunk 3]
```diff
@@ -536,14 +538,14 @@ private void initComponents() {
...
-            meterConditionField.setFont(new Font("Roboto Light", Font.PLAIN, 14));
+            meterConditionField.setFont(ROBOTO_LIGHT_PLAIN_14);
             meterConditionField.setMinimumSize(new Dimension(0, 27));
             mainPanel.add(meterConditionField, "cell 0 0");
 
             //---- label1 ----
             label1.setText("Type");
             label1.setForeground(Color.gray);
-            label1.setFont(new Font("Roboto Light", Font.PLAIN, 15));
+            label1.setFont(ROBOTO_LIGHT_PLAIN_14);
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/status/MeterStatusBar.java]:
```suggestion
            label1.setFont(ROBOTO_LIGHT_PLAIN_15);
```

File: plugin/src/main/java/spp/jetbrains/sourcemarker/status/MeterStatusBar.java [hunk 4]
```diff
@@ -49,6 +48,9 @@
 
 import static spp.jetbrains.marker.SourceMarker.conditionParser;
 import static spp.jetbrains.marker.SourceMarker.creationService;
+import static spp.jetbrains.sourcemarker.PluginUI.COMPLETE_COLOR_PURPLE;
+import static spp.jetbrains.sourcemarker.PluginUI.ROBOTO_LIGHT_PLAIN_14;
```
Comment (BFergerson) [inline plugin/src/main/java/spp/jetbrains/sourcemarker/status/MeterStatusBar.java:52]:
```suggestion
import static spp.jetbrains.sourcemarker.PluginUI.ROBOTO_LIGHT_PLAIN_14;
import static spp.jetbrains.sourcemarker.PluginUI.ROBOTO_LIGHT_PLAIN_15;
```
